//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::event::Entity as Event;
pub use super::host::Entity as Host;
pub use super::prize::Entity as Prize;
pub use super::registrant::Entity as Registrant;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
